/* Bilingual glossary: [topic id, English term, Indonesian term, English definition, Indonesian definition] */
const GLOSSARY = [
  ["units", "physical quantity", "besaran fisika", "Something that can be measured and written as a number with a unit.", "Sesuatu yang dapat diukur dan dinyatakan dengan angka dan satuan."],
  ["units", "SI unit", "satuan SI", "A unit of the International System, such as the metre, kilogram or second.", "Satuan dalam Sistem Internasional, misalnya meter, kilogram, atau sekon."],
  ["units", "base quantity", "besaran pokok", "One of the seven quantities from which all others are defined, such as length, mass and time.", "Salah satu dari tujuh besaran yang menjadi dasar besaran lain, misalnya panjang, massa, dan waktu."],
  ["measurement", "significant figures", "angka penting", "The digits in a measurement that are known reliably.", "Angka-angka dalam hasil pengukuran yang diketahui dengan pasti."],
  ["measurement", "uncertainty", "ketidakpastian", "The range within which the true value of a measurement probably lies.", "Rentang tempat nilai sebenarnya dari suatu pengukuran kemungkinan berada."],
  ["vectors", "vector", "vektor", "A quantity with both size and direction, such as velocity or force.", "Besaran yang memiliki besar dan arah, misalnya kecepatan atau gaya."],
  ["vectors", "scalar", "skalar", "A quantity with size only, such as mass or temperature.", "Besaran yang hanya memiliki besar, misalnya massa atau suhu."],
  ["linear-motion", "displacement", "perpindahan", "The change in position, with direction.", "Perubahan posisi, beserta arahnya."],
  ["linear-motion", "velocity", "kecepatan", "Displacement per unit time; speed with a direction.", "Perpindahan per satuan waktu; kelajuan beserta arahnya."],
  ["linear-motion", "speed", "kelajuan", "Distance travelled per unit time.", "Jarak yang ditempuh per satuan waktu."],
  ["linear-motion", "acceleration", "percepatan", "The rate of change of velocity.", "Laju perubahan kecepatan."],
  ["free-fall", "free fall", "gerak jatuh bebas", "Motion under gravity alone, with acceleration g ≈ 9.8 m/s².", "Gerak di bawah pengaruh gravitasi saja, dengan percepatan g ≈ 9,8 m/s²."],
  ["projectile", "projectile", "benda gerak parabola", "An object moving under gravity alone after it is launched.", "Benda yang bergerak hanya di bawah pengaruh gravitasi setelah dilempar."],
  ["projectile", "range", "jarak mendatar", "The horizontal distance a projectile travels before landing.", "Jarak horizontal yang ditempuh benda sebelum mendarat."],
  ["circular", "centripetal force", "gaya sentripetal", "The net force towards the centre that keeps an object moving in a circle.", "Gaya total ke arah pusat yang menjaga benda tetap bergerak melingkar."],
  ["circular", "angular velocity", "kecepatan sudut", "The angle turned per unit time, in radians per second.", "Sudut yang ditempuh per satuan waktu, dalam radian per sekon."],
  ["newton", "force", "gaya", "A push or a pull; measured in newtons (N).", "Dorongan atau tarikan; diukur dalam newton (N)."],
  ["newton", "inertia", "inersia (kelembaman)", "The tendency of an object to keep its state of motion.", "Kecenderungan benda untuk mempertahankan keadaan geraknya."],
  ["newton", "mass", "massa", "The amount of matter in an object, measured in kilograms.", "Banyaknya materi dalam benda, diukur dalam kilogram."],
  ["newton", "weight", "berat", "The force of gravity on an object, W = mg.", "Gaya gravitasi pada benda, W = mg."],
  ["friction-incline", "friction", "gaya gesek", "A force that opposes sliding between two surfaces.", "Gaya yang melawan gerak geser antara dua permukaan."],
  ["friction-incline", "normal force", "gaya normal", "The force a surface exerts perpendicular to itself.", "Gaya yang diberikan permukaan dengan arah tegak lurus permukaan itu."],
  ["work-energy", "work", "usaha", "Energy transferred by a force moving through a distance, W = Fs.", "Energi yang dipindahkan oleh gaya yang menempuh jarak, W = Fs."],
  ["work-energy", "kinetic energy", "energi kinetik", "The energy of a moving object, ½mv².", "Energi yang dimiliki benda bergerak, ½mv²."],
  ["work-energy", "potential energy", "energi potensial", "Stored energy due to position, such as mgh for height.", "Energi tersimpan karena posisi, misalnya mgh untuk ketinggian."],
  ["work-energy", "power", "daya", "The rate of doing work or transferring energy, in watts.", "Laju melakukan usaha atau memindahkan energi, dalam watt."],
  ["momentum", "momentum", "momentum", "Mass times velocity, p = mv.", "Massa dikali kecepatan, p = mv."],
  ["momentum", "impulse", "impuls", "Force times the time it acts; equal to the change in momentum.", "Gaya dikali lamanya gaya bekerja; sama dengan perubahan momentum."],
  ["rotation", "torque", "momen gaya (torsi)", "The turning effect of a force, force times perpendicular distance.", "Efek putar sebuah gaya, gaya dikali jarak tegak lurus."],
  ["rotation", "moment of inertia", "momen inersia", "How hard it is to change an object's rotation.", "Ukuran seberapa sulit mengubah putaran suatu benda."],
  ["equilibrium", "equilibrium", "kesetimbangan", "A state with zero net force and zero net torque.", "Keadaan ketika gaya total dan momen gaya total sama dengan nol."],
  ["gravitation", "gravitational field", "medan gravitasi", "The region where a mass feels a gravitational force; g is the force per kilogram.", "Daerah tempat massa merasakan gaya gravitasi; g adalah gaya per kilogram."],
  ["gravitation", "orbit", "orbit", "The curved path of one body around another under gravity.", "Lintasan lengkung suatu benda mengelilingi benda lain akibat gravitasi."],
  ["elasticity", "Hooke's law", "hukum Hooke", "The extension of a spring is proportional to the force, F = kx.", "Pertambahan panjang pegas sebanding dengan gaya, F = kx."],
  ["elasticity", "Young's modulus", "modulus Young", "Stress divided by strain; how stiff a material is.", "Tegangan dibagi regangan; ukuran kekakuan suatu bahan."],
  ["fluid-statics", "pressure", "tekanan", "Force per unit area, measured in pascals.", "Gaya per satuan luas, diukur dalam pascal."],
  ["fluid-statics", "buoyancy", "gaya apung (gaya angkat)", "The upward force a fluid exerts on an object in it.", "Gaya ke atas yang diberikan fluida pada benda di dalamnya."],
  ["fluid-dynamics", "Bernoulli's principle", "asas Bernoulli", "Where a fluid flows faster, its pressure is lower.", "Di tempat fluida mengalir lebih cepat, tekanannya lebih rendah."],
  ["center-of-mass", "centre of mass", "pusat massa", "The point where the mass of an object can be treated as concentrated.", "Titik tempat seluruh massa benda dapat dianggap terpusat."],
  ["shm", "simple harmonic motion", "gerak harmonik sederhana", "Oscillation in which acceleration is proportional to displacement and opposite to it.", "Getaran yang percepatannya sebanding dengan simpangan dan berlawanan arah."],
  ["shm", "period", "periode", "The time for one complete oscillation.", "Waktu untuk satu getaran penuh."],
  ["shm", "frequency", "frekuensi", "The number of oscillations per second, in hertz.", "Banyaknya getaran per sekon, dalam hertz."],
  ["mech-waves", "wavelength", "panjang gelombang", "The distance between two neighbouring crests.", "Jarak antara dua puncak gelombang yang berdekatan."],
  ["mech-waves", "amplitude", "amplitudo", "The maximum displacement from the rest position.", "Simpangan terbesar dari posisi setimbang."],
  ["mech-waves", "transverse wave", "gelombang transversal", "A wave that vibrates at right angles to its direction of travel.", "Gelombang yang bergetar tegak lurus arah rambatnya."],
  ["mech-waves", "longitudinal wave", "gelombang longitudinal", "A wave that vibrates along its direction of travel, like sound.", "Gelombang yang bergetar searah rambatnya, seperti bunyi."],
  ["sound", "Doppler effect", "efek Doppler", "The change in observed frequency when the source or listener moves.", "Perubahan frekuensi yang terdengar ketika sumber atau pendengar bergerak."],
  ["heat", "specific heat capacity", "kalor jenis", "The energy needed to raise 1 kg of a substance by 1 °C.", "Energi yang diperlukan untuk menaikkan suhu 1 kg zat sebesar 1 °C."],
  ["heat", "latent heat", "kalor laten", "Energy absorbed or released during a change of state at constant temperature.", "Energi yang diserap atau dilepas saat perubahan wujud pada suhu tetap."],
  ["gases", "ideal gas", "gas ideal", "A model gas that obeys PV = nRT exactly.", "Model gas yang tepat memenuhi PV = nRT."],
  ["gases", "absolute zero", "nol mutlak", "The lowest possible temperature, 0 K or −273.15 °C.", "Suhu terendah yang mungkin, 0 K atau −273,15 °C."],
  ["thermo-laws", "internal energy", "energi dalam", "The total kinetic and potential energy of the particles of a system.", "Jumlah energi kinetik dan potensial partikel-partikel suatu sistem."],
  ["thermo-laws", "entropy", "entropi", "A measure of disorder; it never decreases in an isolated system.", "Ukuran ketidakteraturan; tidak pernah berkurang dalam sistem terisolasi."],
  ["thermo-laws", "efficiency", "efisiensi", "Useful energy out divided by energy in.", "Energi berguna yang keluar dibagi energi yang masuk."],
  ["heat-transfer", "conduction", "konduksi", "Heat transfer through a material without the material moving.", "Perpindahan kalor melalui zat tanpa disertai perpindahan zat."],
  ["heat-transfer", "convection", "konveksi", "Heat transfer by the movement of a fluid.", "Perpindahan kalor disertai aliran fluida."],
  ["heat-transfer", "radiation", "radiasi", "Heat transfer by electromagnetic waves, even through a vacuum.", "Perpindahan kalor melalui gelombang elektromagnetik, bahkan lewat ruang hampa."],
  ["electrostatics", "electric charge", "muatan listrik", "A property of particles that makes them attract or repel; measured in coulombs.", "Sifat partikel yang membuatnya tarik-menarik atau tolak-menolak; diukur dalam coulomb."],
  ["electrostatics", "electric field", "medan listrik", "The region where a charge feels a force; force per unit charge.", "Daerah tempat muatan merasakan gaya; gaya per satuan muatan."],
  ["capacitors", "capacitance", "kapasitansi", "The charge stored per volt, measured in farads.", "Muatan yang tersimpan per volt, diukur dalam farad."],
  ["current-ohm", "electric current", "arus listrik", "The rate of flow of charge, measured in amperes.", "Laju aliran muatan, diukur dalam ampere."],
  ["current-ohm", "voltage (potential difference)", "tegangan (beda potensial)", "The energy per unit charge between two points, in volts.", "Energi per satuan muatan antara dua titik, dalam volt."],
  ["current-ohm", "resistance", "hambatan", "How much a component opposes current, R = V/I, in ohms.", "Seberapa besar komponen menghambat arus, R = V/I, dalam ohm."],
  ["dc-circuits", "series circuit", "rangkaian seri", "A circuit where components are joined one after another in a single loop.", "Rangkaian yang komponennya disambung berurutan dalam satu jalur."],
  ["dc-circuits", "parallel circuit", "rangkaian paralel", "A circuit where components are on separate branches.", "Rangkaian yang komponennya berada pada cabang-cabang terpisah."],
  ["magnetism", "magnetic field", "medan magnet", "The region where a magnet or moving charge feels a magnetic force.", "Daerah tempat magnet atau muatan bergerak merasakan gaya magnet."],
  ["induction", "electromagnetic induction", "induksi elektromagnetik", "Producing a voltage by changing the magnetic flux through a circuit.", "Timbulnya tegangan karena perubahan fluks magnet yang melalui suatu rangkaian."],
  ["induction", "transformer", "transformator (trafo)", "A device that changes the voltage of alternating current.", "Alat untuk mengubah tegangan arus bolak-balik."],
  ["ac", "alternating current", "arus bolak-balik", "Current that reverses direction many times a second.", "Arus yang berbalik arah berkali-kali setiap sekon."],
  ["em-waves", "electromagnetic spectrum", "spektrum elektromagnetik", "The whole range of electromagnetic waves, from radio waves to gamma rays.", "Seluruh rentang gelombang elektromagnetik, dari gelombang radio sampai sinar gamma."],
  ["mirrors", "reflection", "pemantulan", "The bouncing back of light from a surface.", "Pembalikan arah cahaya oleh suatu permukaan."],
  ["mirrors", "focal length", "jarak fokus", "The distance from a mirror or lens to its focal point.", "Jarak dari cermin atau lensa ke titik fokusnya."],
  ["lenses", "refraction", "pembiasan", "The change in direction of light as it passes into another medium.", "Perubahan arah cahaya ketika masuk ke medium lain."],
  ["lenses", "refractive index", "indeks bias", "The speed of light in vacuum divided by its speed in the medium.", "Kecepatan cahaya di ruang hampa dibagi kecepatannya di dalam medium."],
  ["lenses", "total internal reflection", "pemantulan sempurna", "Complete reflection of light inside a denser medium beyond the critical angle.", "Pemantulan seluruh cahaya di dalam medium lebih rapat ketika sudutnya melebihi sudut kritis."],
  ["instruments", "magnification", "perbesaran", "Image size divided by object size.", "Ukuran bayangan dibagi ukuran benda."],
  ["interference", "interference", "interferensi", "The combining of two waves to give a bigger or smaller wave.", "Perpaduan dua gelombang yang menghasilkan gelombang lebih besar atau lebih kecil."],
  ["interference", "diffraction", "difraksi", "The spreading of waves through a gap or around an obstacle.", "Pelenturan gelombang ketika melewati celah atau tepi penghalang."],
  ["relativity", "time dilation", "dilatasi waktu", "Moving clocks run slow compared with clocks at rest.", "Jam yang bergerak berjalan lebih lambat dibanding jam yang diam."],
  ["photons", "photon", "foton", "A packet (quantum) of light energy, E = hf.", "Paket (kuantum) energi cahaya, E = hf."],
  ["photons", "photoelectric effect", "efek fotolistrik", "The release of electrons from a metal when light shines on it.", "Lepasnya elektron dari logam ketika disinari cahaya."],
  ["atoms", "energy level", "tingkat energi", "One of the fixed energies an electron can have in an atom.", "Salah satu energi tertentu yang dapat dimiliki elektron dalam atom."],
  ["radioactivity", "half-life", "waktu paruh", "The time for half of the radioactive nuclei in a sample to decay.", "Waktu yang dibutuhkan agar separuh inti radioaktif dalam sampel meluruh."],
  ["radioactivity", "isotope", "isotop", "Atoms of the same element with different numbers of neutrons.", "Atom-atom unsur yang sama dengan jumlah neutron berbeda."],
  ["nuclear-energy", "nuclear fission", "fisi nuklir", "The splitting of a heavy nucleus into lighter ones, releasing energy.", "Pembelahan inti berat menjadi inti yang lebih ringan dengan melepaskan energi."],
  ["nuclear-energy", "nuclear fusion", "fusi nuklir", "The joining of light nuclei into a heavier one, releasing energy.", "Penggabungan inti-inti ringan menjadi inti lebih berat dengan melepaskan energi."],
  ["renewables", "renewable energy", "energi terbarukan", "Energy from sources that are naturally replaced, such as sunlight, wind and water.", "Energi dari sumber yang terus diperbarui secara alami, seperti sinar matahari, angin, dan air."],
  ["electronics", "semiconductor", "semikonduktor", "A material, such as silicon, whose conductivity lies between a conductor and an insulator.", "Bahan, misalnya silikon, yang daya hantarnya di antara konduktor dan isolator."],
  ["electronics", "diode", "dioda", "A component that lets current flow in one direction only.", "Komponen yang hanya mengalirkan arus ke satu arah."]
];
